### ISSUE TITLE
[Feature Request] GetCapabilities from light

### ISSUE THREAD

**Issue by samclane** [mclarkk/lifxlan#104]
I saw in the LIFX API that the `List Lights` method ([documented here](https://api.developer.lifx.com/docs/list-lights)) has a field in the return called `capabilities`, which lists the min and max kelvin in addition to the other operational functions of the light. I know that this is the Web API (not the LAN one which lifxlan uses), but I wondered if there was an equivalent in the LAN messaging scheme. I know it's a distinct possibility this info isn't being stored locally on the bulbs, and instead is combined with the bulb info serverside, then sent to the client. But even the [products.json](https://github.com/LIFX/products/blob/master/products.json) doesn't have this info (although it has all the rest of the info).

Thanks.

**Comment by mclarkk** [comment]
[Here's a link to a 2016 LIFX forum discussion about this topic.](https://community.lifx.com/t/kelvin-ranges-for-all-models/846) The Illustrious Daniel Hall provides the following values:

> 2700K-6500K for White 800 (both Low and High Voltage), White 900 BR30
2500K-9000K for Original 1000, Color 650, Color 1000, Color 900 BR30

It looks like the values for the remaining products can be found on product sheets.

**Comment by mclarkk** [comment]
Excellent, PR accepted! Thank you!
