### ISSUE TITLE
Releases ?

### ISSUE THREAD

**Issue by autolog** [mclarkk/lifxlan#106]
With the latest Kelvin Min/Max change - should the LIFXLAN version have been upped in /__init__.py ?

It would be useful with each version change if it was packaged and added to the Releases section. There would then be a history of versions with the ability to easily go back a release if required.

Thanks for considering. :)

**Comment by mclarkk** [comment]
I usually only change the version number before releasing a new version on PyPI, and I haven't released the Kelvin min/max change to PyPI yet (though I probably should). 

PyPI automatically creates a [version history](https://pypi.org/project/lifxlan/#history) and allows you to install previous releases (e.g., `pip install lifxlan==1.2.2`)...does this do what you want, or is there something PyPI still lacks?

**Comment by autolog** [comment]
I normally download the source rather than using pip to install. I am embedding the lifxlan library in my Indigo plugin. So using pip doesn't really work for me. That's why having it in releases as well would be helpful. Not a problem if you don't think it is appropriate to do this. :)
