### ISSUE TITLE
[Feature Request] provide a minimal commandline tool

### ISSUE THREAD

**Issue by jordancoll** [mclarkk/lifxlan#121]
something like `python -m lifxlan -n 1 set_power 0` to run `LifxLAN(1).set_power_all_lights(0)`

**Comment by DrTexx** [comment]
Hi :)

Unsure if it's still relevant, however I created something last year for this called `CLIFX`.

The repository is currently set to private; I'll quickly go swap it over to public and drop a link here :)

**Comment by DrTexx** [comment]
Done!

Here's a link: https://gitlab.com/DrTexx/CLIFX

Twitter DMs are the best way to reach me (`@drtexx`), lmk if you need anything and happy to help :) :+1:

**Comment by mathiashro** [comment]
@DrTexx : You repository seems to require a login. May be it's not public yet?

**Comment by Tamooj** [comment]
It's a gitlab repo, not github

**Comment by DrTexx** [comment]
> @DrTexx : You repository seems to require a login. May be it's not public yet?

@mathiashro oh weird? Sorry I missed your reply earlier. Is it working now?

> It's a gitlab repo, not github

@Tamooj yeah that might've been the issue @mathiashro hit. Shouldn't require a login unless you're looking to do something like star the repo or create a PR

**Comment by mathiashro** [comment]
Hello @DrTexx, I can confirm your Gitlab-based repo is now public readable. Thank you.

**Comment by DrTexx** [comment]
Awesome! :)

Thanks for confirming! 🥳
