### ISSUE TITLE
set_power(state,duration,rapid) not working

### ISSUE THREAD

**Issue by masterchop** [mclarkk/lifxlan#124]
After testing the module, i found out that the duration option is not available, i am not able to set the duration of my action. Its always instant.

>>> pcl.set_power("off",5,False)
>>> pcl.set_power("on",5,True)

**Comment by samclane** [comment]
You have to sleep after the first call to allow time to fade. Otherwise you're just sending the next command immediately after.

**Comment by masterchop** [comment]
I open a new thread to send the action, and thread dies when its done. Thanks. the sleep option froze the script and i needed to do other stuff :)
