### ISSUE TITLE
Discovery problem - Product List out-of-date

### ISSUE THREAD

**Issue by autolog** [mclarkk/lifxlan#138]
I use this library in the LIFX plugin for Indigo (Mac Home Automation). Some users of the plugin are reporting that bulbs with the latest firmware (3.5 / 3.6) are not being discovered when running a discovery (earlier version firmware bulbs are discovered OK).

As I haven't got any bulbs with updated firmware, I was wondering whether anyone else has experienced this and as to whether there is a fix / workaround?

**Comment by autolog** [comment]
I have done further investigations on this and it appears that a bulb with newer firmware has a different product code? Specifically, a BR10 with new firmware 3.6 is product code 63. I was able to get round the issue for one of my users by replicating product 44 > 63. I note that the [LIFX Products documentation](https://lan.developer.lifx.com/docs/lifx-products) on the LIFX Developer site doesn't yet include this new model. I suspect there may be other models not yet handled. I have added an error message to my Indigo plugin to flag up discovered but unknown products.

**Comment by autolog** [comment]
Created an issue on the [LIFX Developer Zone](https://community.lifx.com/t/lifx-product-list-out-of-date/6236) for this issue.

**Comment by autolog** [comment]
It looks like there are two new products with Ids 62 and 63 - see response from LIFX in the LIFX Developer Zone.

**Comment by autolog** [comment]
LIFX have now updated the [LIFX Product Definition on Github](https://github.com/LIFX/products/blob/master/products.json) as at 6th January 2020.

I note that the json file also contains "matrix"  entries for each bulb which are only set to true for Tiles and Candles?

I also note that in **lifxlan.py**, the **discover_devices** method defaults to a light if it gets an exception (Comment: # cheating -- it just so happens that all LIFX devices are lights right now) but sets no default if product id isn't found. Maybe the method should set a default LIFX lamp with a model name of **UNKNOWN PRODUCT nn** or similar?

**Comment by mclarkk** [comment]
Updated product list with #153. Also, added default product for when the product ID is not known -- great idea!
