### ISSUE TITLE
Add Support For Candle Color bulbs

### ISSUE THREAD

**Issue by frakman1** [mclarkk/lifxlan#140]
Is there any chance you could add support for the new LIFX candle color bulbs?

The product link is [here](https://www.lifx.com/products/candle-color)

When I ran `hello_world.py`, it saw all my other LIFX bulbs but not the new candle color ones.

The new[ product ID](https://lan.developer.lifx.com/docs/lifx-products) is 68

**Comment by mclarkk** [comment]
Hey Frak! A fix for this was merged a few months ago, should be there if you pull and reinstall from source: https://github.com/mclarkk/lifxlan/pull/135

**Comment by frakman1** [comment]
Great. Thank you. I guess I should have checked first. 
I just tried it and it works with my bulbs now.

**Comment by pcfidelity** [comment]
Hello, 

Just to note the candle colour is a chain device with 26 zones (https://uk.lifx.com/products/candle-color). It works fine just by changing chain setting in products.py to true. Mine is device ID 57.

Thanks for making LifxLAN - got it working with no prior python experience in under an hour!

**Comment by pcfidelity** [comment]
Some more useful information here by the way:
https://community.lifx.com/t/updating-the-http-api-and-lan-protocol-docs-for-the-candle-colour/6376

It doesn't work with the Tile setting (at least on the v3.50 firmware) by the way despite this post describing it as tiles.
