### ISSUE TITLE
Upgraded GU10's from 3.42 -> 3.60 firmware, now can't be discovered

### ISSUE THREAD

**Issue by ps-jay** [mclarkk/lifxlan#146]
Hi all,

Two of my GU10's upgraded from 3.42 firmware to 3.60, and now `get_devices()` fails to discover them.
I still have one GU10 on the 3.41 firmware, and it can be discovered.

Has anyone experienced this?  Is it related to #138 ?

I'm happy to contribute code if someone can give me pointers on how to troubleshoot.

Regards,
  Phil

**Comment by ps-jay** [comment]
Hi again,

it looks to me like the 3.60 firmware does not like the [source_id](https://github.com/mclarkk/lifxlan/blob/e42240b/lifxlan/lifxlan.py#L24) being set to `1`.

If I alter `self.source_id` to be hardcoded to value for example, then I can discover 3.60 firmware GU10's.

I'm running LifxLAN in a Docker container, so the `os.getpid()` method is returning `1` - triggering the issue.

I'll raise a PR in the next few days to address this.

**Comment by mclarkk** [comment]
Great discovery! I'll take a look at the PR shortly.

**Comment by ps-jay** [comment]
Closed via #148
