### ISSUE TITLE
Newest "LIFX Color A19 1100 lm" bulbs not recognized as color bulbs

### ISSUE THREAD

**Issue by bobpendleton** [mclarkk/lifxlan#158]
My older bulbs are all working fine.  But unlike my older Model "LIFX (A19)" bulbs (which are on firmware version 2.72) the newer bulbs (finally back in stock), which show up as Model "LIFX Color A19 1100lm" in the LIFX app and are running v3.70 firmware, are not recognized as color bulbs. 

supports_color() returns FALSE.  get_color and set_color both result in the "AttributeError: 'Device' object has no attribute" error.

Is there any workaround for this?  Thanks in advance for the help!

**Comment by autolog** [comment]
I was thinking about doing another pull-request but it appears that it may be a bit more complicated than I anticipated.

The definition (undocumented in the Developer LIFX docs) is I think as follows to be added to the **features_map** in products.py:`                93: {                    # LIFX Color A19 1100lm (UNDOCUMENTED)
                    "color": True,
                    "temperature": True,
                    "infrared": False,
                    "multizone": False,
                    "chain": False,
                    "matrix": False,
                    "min_kelvin": 1500,
                    "max_kelvin": 9000,
                    "hev": False,
                    "relays": False,
                    "buttons": False},
`

Also need to add: `93: "LIFX Color A19 1100lm",` into the **product_map** at the start of products.py and add `93, ` into **light-products** line following the **product_map** in products.py.

**Comment by bobpendleton** [comment]
Thanks so much for the fast reply. I made all three of those changes to the products.py file (located in the "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python38\Lib\site-packages\lifxlan" directory on my Windows 10 machine) and it worked perfectly.

Thanks again!
