### ISSUE TITLE
Link to onboarding script in readme &/or provide onboarding support

### ISSUE THREAD

**Issue by rsyring** [mclarkk/lifxlan#163]
Thanks so much for your work on this library!

I wanted to onboard the light without having to create a user account or use their mobile apps.  I found a Python script that did it but it took some digging:

https://github.com/tserong/lifx-hacks/blob/master/onboard.py

Could you link to this in the readme and/or provide an API for onboarding support in the lifxlan library?

**Comment by seniorm0ment** [comment]
how did you use  that curiously? 
did you just do
 ./script.py ssid password
? or did you have to edit anything in it
