### ISSUE TITLE
On a computer with multiple NICs including onese from hyper-v and vmware I am getting  -> OSError: [WinError 10051] A socket operation was attempted to an unreachable network error. 

### ISSUE THREAD

**Issue by Aiddy81** [mclarkk/lifxlan#186]
I've downloaded the latest version of this library and have both hyper-v and vmware virtual apdaters on my computer and am getting this OSError: [WinError 10051] A socket operation was attempted to an unreachable network error.

Similar to #164 

These are what the adapters look like on my system
![image](https://github.com/mclarkk/lifxlan/assets/21276456/7eb09e5e-889b-4f31-ac07-0ef0cc5362a4)

**Comment by mclarkk** [comment]
I'm guessing you installed lifxlan via `pip`, which did not have the fix in https://github.com/mclarkk/lifxlan/pull/165 until this morning. Please upgrade to the latest version with `pip install lifxlan --upgrade`.
