### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by brutevinch** [mclarkk/lifxlan#2]
I don't know why it doesn't work. (
root@debian:/usr/src/lifxlan/examples# python rainbow_all.py 

Discovery will go much faster if you provide the number of lights on your LAN:
  python rainbow_all.py <number of lights on LAN>

Discovering lights...
Traceback (most recent call last):
  File "rainbow_all.py", line 49, in <module>
    main()
  File "rainbow_all.py", line 20, in main
    original_colors = lifx.get_color_all_lights()
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/lifxlan.py", line 88, in get_color_all_lights
    responses = self.broadcast_with_resp(LightGet, LightState)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/lifxlan.py", line 186, in broadcast_with_resp
    response = unpack_lifx_message(data)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/unpack.py", line 153, in unpack_lifx_message
    label = "".join([chr(b) for b in struct.unpack("b"*32, payload_str[12:44])])
ValueError: chr() arg not in range(256)

**Comment by brutevinch** [comment]
root@debian:/usr/src/lifxlan/examples# python blink_all.py 

Discovery will go much faster if you provide the number of lights on your LAN:
  python blink_all.py <number of lights on LAN>

Discovering lights...
Turning lights on...
Toggling power of all lights...
Restoring power to all lights...
Traceback (most recent call last):
  File "blink_all.py", line 81, in <module>
    main()
  File "blink_all.py", line 37, in main
    original_colors = lifx.get_color_all_lights()
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/lifxlan.py", line 88, in get_color_all_lights
    responses = self.broadcast_with_resp(LightGet, LightState)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/lifxlan.py", line 186, in broadcast_with_resp
    response = unpack_lifx_message(data)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/unpack.py", line 153, in unpack_lifx_message
    label = "".join([chr(b) for b in struct.unpack("b"*32, payload_str[12:44])])
ValueError: chr() arg not in range(256)

**Comment by brutevinch** [comment]
Cyrilic name problem

**Comment by mclarkk** [comment]
Reopening this issue, since Cyrillic names shouldn't be a problem. The package should be modified to support Unicode.

**Comment by brutevinch** [comment]
Ok. i will be happy to rename my bulb,room,house to my lang.

**Comment by mclarkk** [comment]
Can you run verbose_lan.py and paste the output of the StateLabel message here? I'd be interested to see how the unicode is being represented in binary.

**Comment by brutevinch** [comment]
Yes of course. i rename to cyrillic back and now i've got 
Found Bulbs:
  None
But iOS app works at same time.

**Comment by mclarkk** [comment]
Sorry sorry, can you do a `git pull` and then `sudo python setup.py install`, then run verbose_lan.py? In particular, I am interested in this message:

RECV: StateLabel
  Size: 68
  Origin: 1
  Tagged: 0
  Protocol: 1024
  Source ID: 812003224
  Target MAC Address: d0:73:d5:00:70:36
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 25
  Payload:
    Label: Lotus Lamp
  Bytes:
    ['0x44', '0x0', '0x0', '0x54', '0x98', '0x2f', '0x66', '0x30', '0xd0', '0x73', '0xd5', '0x0', '0x70', '0x36', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0x84', '0x9b', '0x91', '0x77', '0x39', '0x80', '0xef', '0x13', '0x19', '0x0', '0x0', '0x0', '0x4c', '0x6f', '0x74', '0x75', '0x73', '0x20', '0x4c', '0x61', '0x6d', '0x70', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0']

**Comment by brutevinch** [comment]
When i rename to cyr there is no RECV: StateLabel in output of verbose_lan.py. But when i rename back to test i've got this:

RECV: StateLabel
  Size: 68
  Origin: 1
  Tagged: 0
  Protocol: 1024
  Source ID: 2844531751
  Target MAC Address: d0:73:d5:01:b6:9f
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 25
  Payload:
    Label: Test
  Bytes:
    ['0x44', '0x0', '0x0', '0x54', '0x27', '0x1c', '0x8c', '0xa9', '0xd0', '0x73', '0xd5', '0x1', '0xb6', '0x9f', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0x4', '0x26', '0x91', '0x9c', '0x81', '0x81', '0xef', '0x13', '0x19', '0x0', '0x0', '0x0', '0x54', '0x65', '0x73', '0x74', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0']

Found Bulbs:
  Test
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@debian:/usr/src/lifxlan/examples# python verbose_lan.py | grep StateLabel
root@debian:/usr/src/lifxlan/examples# python verbose_lan.py | grep StateLabel
RECV: StateLabel
First try with cyr name. Second is eng.

**Comment by mclarkk** [comment]
That is interesting! In that case, do you mind posting the entire output of verbose_lan.py when using Cyrillic? It'll be long, but that's okay.

**Comment by brutevinch** [comment]
Here is output of verbose_lan.py: http://pastebin.com/Yd1XKjy5

**Comment by mclarkk** [comment]
Huh! There isn't even an alternative message with an undocumented format. Looks like unicode labels just aren't getting sent back. I'll ask the LIFX folks about it. Until then, I'll close this issue.

**Comment by frakman1** [comment]
Did you ever hear back from LIFX about this?

**Comment by mclarkk** [comment]
Here was their response:
https://community.lifx.com/t/bulb-with-unicode-label-not-sending-statelabel-message/98

Basically, even with a Cyrillic label the bulb should still just send back
the bytes that correspond to the label. To figure what is going on, I would
need to replicate the bug on my end and then pcap the interaction (which I
haven't done), or if I couldn't replicate the bug, brutevinch would need to
pcap their interaction.

**Comment by brutevinch** [comment]
Hi! Sorry, can't understand...what i must to do? To replicate the bug just rename: "House" to "Дом", "Bedroom" to "Спальня", "Nightlight" to "Ночник"

**Comment by frakman1** [comment]
mclarkk: I guess it's time to brush up on your Cyrillic. haha

**Comment by brutevinch** [comment]
I guess = "Я полагаю" or synonym "i think" = "Я думаю"
it's time to = "Самое время"
brush up = "Освежить" (synonym "make fresh")
=D Free translate) Sorry for spam.
