### ISSUE TITLE
Python3 not working (solved)

### ISSUE THREAD

**Issue by frawau** [mclarkk/lifxlan#20]
Hi Meghan,

First thanks for sharing your work. I used it with python 2.7 and it was working great. But now I want python 3.5.

I was trying to use lifxlan with python 3.5 and it was not working. So I made it work whilst keeping python 2 (2.7.12) working too. All the examples that is, there may still be some problems lurking around. The "git diff" file is attached

I any case it seem to indicate some issue with the way you handle the labels as a string and as a bytes string....but I did not investigate too deeply... it may be due to the Python rev.

Next I'll see how to get it to work with asyncio and see if I can get something in the IPv6 domain...since I can ping6 my bulbs.

Cheers,
        François

[lifxlan-diff.txt](https://github.com/mclarkk/lifxlan/files/478072/lifxlan-diff.txt)

**Comment by mclarkk** [comment]
I'm very excited about this, as I know others have wanted a Python 3 compatible version as well. I'm currently traveling, but I'll look into this soon and hopefully we can get a version up that works with Python 2 and 3! Thanks!

**Comment by frawau** [comment]
Well... what I did was pretty trivial... update the imports to add a dot in front of the module name and try to fix the fact that in 2.7 the label is a string whilst in python 3 it is a bytestring.  Not rocket science.

Anyway, if your travels bring you to Bangkok, I'll buy you a drink .

**Comment by mclarkk** [comment]
I finally incorporated your changes into the library, with some extra changes for the new files that have been added since then :) Thanks a ton!

**Comment by frawau** [comment]
No problem. BTW, I took your mod'ed code and made a asyncio compatible library called aiolifx. Thanks to asyncio, discovery is a lot faster.

You did the hard work so thank you ;)
