### ISSUE TITLE
Preset RED not correct

### ISSUE THREAD

**Issue by RichStevenson** [mclarkk/lifxlan#22]
Run ./broadcast_color.py red, and then check with ./get_color_all.py
Lights are set to  HSBK: (62978, 65535, 65535, 3500) instead of  HSBK: (65535, 65535, 65535, 3500) as specified in the Lights.py.

Edit: Should have also mentioned I installed with pip, and the RED preset is incorrect in that Lights.py.

**Comment by mclarkk** [comment]
Amazing catch! I'll be releasing a new version onto PyPi in the next few weeks thanks to some nice pull requests that have added support for the LIFX Z and setting waveforms, so the pip version will be fixed then. In the meantime, installing from source should fix it (I had to uninstall my pip version first).
