### ISSUE TITLE
Support MultiZone

### ISSUE THREAD

**Issue by frakman1** [mclarkk/lifxlan#24]
Is there any chance you could add support for the new LIFX light strip's multi-zone capability?

The protocol documentation is [here](https://lan.developer.lifx.com/docs/multizone-light-control)
The product link is [here](http://www.lifx.com/products/lifx-z)

**Comment by mclarkk** [comment]
What great timing! I just merged a pull request from @psubrownie that adds multi-zone support. Can you pull, rebuild, and confirm that it works for you? (I don't have a light strip to test on.)

**Comment by frakman1** [comment]
I tested it quickly this morning by using the multizone.py file in examples and it seems to work fine. I can't wait to start playing with it. Thank you!

**Comment by psubrownie** [comment]
Just FYI, my LIFX Z keep dropping off the network while running that chase example.  Even at only sending commands every 5 seconds.  I'm going to open an issue with LIFX support.  I'm so happy I was able to contribute to this.  I'm not normally a Python developer, so their might be some slop, but it does work, as long as the strip stays on the network.  The math on the Chase effect wrapping around the end was a pain, but thats the effect I wanted to do.

**Comment by mclarkk** [comment]
Thanks for contributing, psubrownie! I hope you figure out the issue with your bulbs.
