### ISSUE TITLE
SetWaveform doesn't work like it should (likely a bulb firmware issue)

### ISSUE THREAD

**Issue by mclarkk** [mclarkk/lifxlan#26]
NOTE: Set Waveform is currently an experimental undocumented feature of the LIFX bulbs.

is_transient=1 is supposed to set the light back to its original color after the waveform according to some pull requests for the LIFX LAN protocol docs: https://github.com/LIFX/lifx-protocol-docs/pull/12/commits/8a38d3d5060bd6cba562fa940459d9b637d55726

Instead, currently is_transient=1 results in bulbs staying on the last color of the waveform instead of original color. At this point I'm 99.9% sure this is a problem with the bulbs, not the code, but I'm submitting it here as an issue to document the behavior and keep an eye on it as LIFX develops their protocol.

**Comment by ceboxsell** [comment]
Looks like the latest firmware has resolved this. Seems to be working nicely so far on my Z

**Comment by mclarkk** [comment]
Mine too! Yay!
