### ISSUE TITLE
Bulb not responding when instantiating Light object with MAC and IP addresses

### ISSUE THREAD

**Issue by jusmop** [mclarkk/lifxlan#39]
I have 2 LIFX colour 1000 bulbs. Both work with the Android app and both work when using the example scripts under lifxlan/examples (these scripts all use device discovery). This includes the scripts which read the bulb colour and power etc.

However when I instantiate a Light object with a MAC and IP addresses, one bulb responds and one doesn't. I can control both bulbs (set colour, power, etc), but do not receive acknowledgements.

Since the example scripts work, I don't think I have a hardware problem. But I don't understand how my very basic scripts work with one bulb and not the other. Yes I have triple checked the obvious - MAC addr and IP addr.

E.g. 
~/lifxlan/examples$ ./get_color_all.py

Discovery will go much faster if you provide the number of lights on your LAN:
  python ./get_color_all.py <number of lights on LAN>

Discovering lights...
Right (d0:73:d5:14:23:af 192.168.2.30) HSBK: (29814, 0, 65535, 5500)
Left (d0:73:d5:14:1e:ac 192.168.2.29) HSBK: (0, 0, 24575, 3000)

But if I run the following script snippet:
def test():
	left = lifxlan.Light("d0:73:d5:14:1e:ac", "192.168.2.29")
	print left.get_color()
	right = lifxlan.Light("d0:73:d5:14:23:af", "192.168.2.30")
	print right.get_color()

I get:
~/lifxlan/examples$ ./test.py
(0, 0, 24575, 3000)
WorkflowException: Did not receive [<class 'lifxlan.msgtypes.LightState'>] from d0:73:d5:14:23:af (Name: None) in response to <class 'lifxlan.msgtypes.LightGet'>
None

Do you have any suggestions?

Thanks.

**Comment by jusmop** [comment]
I'm embarrassed to say that the old Microsoft trick worked - power cycling the bulb. Which I thought I had done, but apparently not.

Looks like the bulb was in some sort of odd state. All good now.

**Comment by mfarley281** [comment]
This happens to me all the time. I think the LIFX bulbs are extra sensitive to any disruption in wifi signals.

**Comment by mclarkk** [comment]
Great! I'm glad it's working now! Let me know if you start to see similar problems again. I have an idea for something to try next time. 

I have a few bulbs that are further away from my router. Alexa often has trouble controlling these lights, even though she never has problems controlling the lights close to the router. When I open up my LIFX app, it runs discovery (broadcasts a GetService message) so that it can populate the display with the available lights and their current state. Usually the problematic lights start off disconnected according to the app, but then reconnect and show up within a few seconds of discovery. Once the lights are reconnected according to the app, it's like they've "woken up" and control via Alexa works again. 

I think the mechanism that the app uses to reconnect the lights is sending the GetService message. So if you have trouble with your lights again, it might work to add the following to line 26 of light.py (at the end of the Light object constructor): 

```
try:
    response = self.req_with_resp(GetService, StateService)
except WorkflowException as e:
    print (e)
```

This will send the light a GetService discovery message once upon instantiation. It won't take as long as the LAN-wide discovery process because you're communicating directly with the light instead of waiting for some unknown number of devices to respond. Sending the light a discovery message might be enough to "wake it up" and work, just like it was working after normal discovery.

**Comment by jusmop** [comment]
Thanks for the suggestion. I'll test the change next time I see the issue.
Cheers!

**Comment by jusmop** [comment]
Hi,

I tested your suggestion today after both my bulbs showed the problem described by this ticket. Unfortunately your suggestion didn't work. I update to the latest repository version using git pull. My test script:

#!/usr/bin/env python
import lifxlan
import sys

def main():
    left = lifxlan.Light("d0:73:d5:14:1e:ac", "192.168.2.29")
    left.req_with_resp(lifxlan.GetService, lifxlan.StateService)

if __name__=="__main__":
    main()

Output:
  File "./test.py", line 7, in main
    left.req_with_resp(lifxlan.GetService, lifxlan.StateService)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.4.0-py2.7.egg/lifxlan/device.py", line 472, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.device.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.StateService'>] from d0:73:d5:14:1e:ac (Name: None) in response to <class 'lifxlan.msgtypes.GetService'>

Any ideas?

**Comment by jusmop** [comment]
To add some info:
* The example scripts work on both my bulbs.
* The Android LIFX app works fine.
* Instantiating a Light object with a MAC and IP address _after_ running an example script (e.g. to "wake the bulb up") doesn't work.

I guess I'm going to have to do the discovery thing each time my script runs.

**Comment by mclarkk** [comment]
I'm sorry that didn't work, I guess my intuition about why it might work with discovery but not MAC/IP ended up being incorrect.

Can you run the `hello_world.py` example and paste the output here? Your MAC and IP address are probably correct, but it would also be helpful to see the port, model information, firmware version, WiFi signal strength, etc. Feel free to anonymize location/group if you want.

**Comment by jusmop** [comment]
I did a git pull, setup.py install (both python and python3 as I use the latter) then ran hello_world.py. Output:

justin@juka:~/lifxlan/examples$ ./hello_world.py 

Discovery will go much faster if you provide the number of lights on your LAN:
  python ./hello_world.py <number of lights on LAN>

Discovering lights...

Found 2 light(s):

Left
  MAC Address: d0:73:d5:14:1e:ac
  IP Address: 192.168.2.29
  Port: 56700
  Service: UDP
  Power: On
  Location: My Home
  Group: Living Room
  Color (HSBK): (43634, 0, 45874, 3500)
  Host Firmware Build Timestamp: 1485471208000000000 (2017-01-26 22:53:28 UTC)
  Host Firmware Build Version: 1.21
  Wifi Firmware Build Timestamp: 1456093684000000000 (2016-02-21 22:28:04 UTC)
  Wifi Firmware Build Version: 101.62
  Vendor: 1
  Product: 22 (Color 1000)
  Version: 0
  Features: {'color': True, 'multizone': False, 'infrared': False}
  Current Time: 1492423351710714000 (2017-04-17 10:02:31 UTC)
  Uptime (ns): 461470046000000 (128.19 hours)
  Last Downtime Duration +/-5s (ns): 0 (0.0 hours)
  Wifi Signal Strength (mW): 0.00010000000475
  Wifi TX (bytes): 39644335
  Wifi RX (bytes): 1288380780

Right
  MAC Address: d0:73:d5:14:23:af
  IP Address: 192.168.2.30
  Port: 56700
  Service: UDP
  Power: On
  Location: My Home
  Group: Living Room
  Color (HSBK): (43634, 0, 42601, 3500)
  Host Firmware Build Timestamp: 1485471208000000000 (2017-01-26 22:53:28 UTC)
  Host Firmware Build Version: 1.21
  Wifi Firmware Build Timestamp: 1456093684000000000 (2016-02-21 22:28:04 UTC)
  Wifi Firmware Build Version: 101.62
  Vendor: 1
  Product: 22 (Color 1000)
  Version: 0
  Features: {'color': True, 'multizone': False, 'infrared': False}
  Current Time: 1492423351827320000 (2017-04-17 10:02:31 UTC)
  Uptime (ns): 456850296000000 (126.9 hours)
  Last Downtime Duration +/-5s (ns): 0 (0.0 hours)
  Wifi Signal Strength (mW): 6.3095767473e-06
  Wifi TX (bytes): 39362648
  Wifi RX (bytes): 1275534703

**Comment by mclarkk** [comment]
Hm, unfortunately I don't see anything there that looks weird. Latest firmware, port 56700, and the WiFi signal strength looks sufficient (though I've noticed it will fluctuate a surprising amount on mine). Last time you fixed this problem by power cycling the bulbs. Did that not fix it this time?

**Comment by mclarkk** [comment]
I just pushed a fix to the repo and PyPI that fixed a networking issue the library had with Microsoft Windows. I don't know if it will fix the problem you were having, but it might!

**Comment by tkg61** [comment]
Just wanted to comment and say that i am having a similar issue. 

line 297, in broadcast_with_resp
    raise WorkflowException("Did not receive {} in response to {}".format(str(response_type), str(msg_type)))
lifxlan.errors.WorkflowException: Did not receive <class 'lifxlan.msgtypes.LightStatePower'> in response to <class 'lifxlan.msgtypes.LightGetPower'>


I have tried:
-  the routing fix (changing 255.255.255.255)
-  the above fixes (changing light.py and also trying pip fix),
-  rebooting lightbulb
-  setting ip/mac statically
- discovery via broadcast
- verbose_lan.py doesn't find anything
- sniffer.py doesn't see any traffic when using the app
- The lifx app does control the bulb
- verbose output from LifxLan() looks like the above 
- None of the example scripts work
- I can ping my bulb from my computer (windows 10)

I'll be happy to try anything or provide more information. Let me know if i should open a new ticket

Thanks,

**Comment by mclarkk** [comment]
What version of `lifxlan` are you using?
Does it work if you turn off your firewall completely?
How many network interfaces do you have? 
What is your local subnet? (192.161.1? 10.0.0? Etc?)
What gets returned if you run this function in the python interpreter?

```
from socket import AF_INET, SOCK_DGRAM, socket, timeout, gethostbyname_ex, gethostname
import platform

def get_broadcast_addr():
    # This fix exists for Windows machines that can't handle 255.255.255.255
    # It tries to get the local subnet's broadcast address (192.168.1.255, 10.0.0.255, etc.)
    if platform.system() == 'Windows':
        local_ip = [l for l in ([ip for ip in gethostbyname_ex(gethostname())[2] if not ip.startswith("127.")][:1], [[(s.connect(('8.8.8.8', 53)), s.getsockname()[0], s.close()) for s in [socket(AF_INET, SOCK_DGRAM)]][0][1]]) if l][0][0]
        ip_parts = local_ip.split(".")
        ip_parts[-1] = "255"
        broadcast = ".".join(ip_parts)
    else:
        broadcast = "255.255.255.255"
    return broadcast
```

**Comment by tkg61** [comment]
Thanks for the reply. 

With your script i was able to see that my broadcast subnet was incorrect. This was due to a virtualbox host adapter on my system. After disabling it, both broadcast commands and static (MAC/IP) commands work!

Thanks for the help! I hope this helps someone else too.

**Comment by mclarkk** [comment]
Awesome! Glad you were able to figure it out!
