### ISSUE TITLE
Light object and MultiZone

### ISSUE THREAD

**Issue by soljarag** [mclarkk/lifxlan#40]
is it just me, or does MultiZone  not work with Light object?

I have a known MAC and IP of my Lighstrip.... so I'm tying to use a Light object to control the zones....

I can control the entire light with the Light object...

**Comment by mclarkk** [comment]
Correct, to use the MultiZone features you will have to instantiate your lightstrip as a MultiZoneLight object rather than a Light object. The constructor is similar: MultiZoneLight(mac_addr, ip_addr). I just added a couple of sentences to the README to clarify that.
