### ISSUE TITLE
Synchronizing command execution on/off

### ISSUE THREAD

**Issue by Kirillism** [mclarkk/lifxlan#41]
Like the title states, is it possible to synchronize command execution? I have two lights and using the following code to toggle them on/off they execute in sequence (the first Light() in the list executes faster than the second Light() in the list). Is there a way to let them execute the commands in parallel? I've tried applying the following threading, but alas it didn't work:
https://pymotw.com/2/threading/

My code:
>         power = self.lights[0].get_power() 
>         for light in self.lights:
>            try:
>                light.set_power("on" if power == 0 else "off")
>            except:
>                print(sys.exc_info()[0])  # TODO replace with logging

**Comment by mfarley281** [comment]
I had the same use case / issue and am using this code to send the requests asynchronously: http://pastebin.com/drfx0tAU

**Comment by Kirillism** [comment]
Thank you, will try that tomorrow!

**Comment by Kirillism** [comment]
@mfarley281 your solution has worked for me, thank you!

**Comment by mclarkk** [comment]
@mfarley281 @Kirillism You can also set `rapid=true`,  as in `light.set_power("on" if power == 0 else "off", true)`. The `rapid` flag will send commands without waiting for the ACK. If you really need both non-blocking send and an ACK, then @mfarley281's solution is the best, but I have found that setting `rapid=true` is a simple fix that generally works.
