### ISSUE TITLE
Issue with python3 pip

### ISSUE THREAD

**Issue by LucaCerina** [mclarkk/lifxlan#45]
Hi, I wanted to notice you that the installation of lifxlan on python3 with pip seems to be broken because it collects the data, executes the setup, but then every file of the library is empty and the instatiation of the class responds with:

'lifxlan has no attribute LifxLAN'

The Python2/pip2 version works correctly

**Comment by mclarkk** [comment]
I wasn't able to replicate this issue. I tried it with pip for Python 3.6 and 3.3, both worked fine for me.
