### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by frakman1** [mclarkk/lifxlan#6]
I tried installing lifxlan on a different Win7 (64bit AMD chipset) machine.  Running the broadcast scripts return immediately with no output and hello_world.py returns a run-time error:

```
c:\Python27\lifxlan-master\lifxlan-master\examples>python broadcast_off.py

c:\Python27\lifxlan-master\lifxlan-master\examples>python broadcast_off.py

c:\Python27\lifxlan-master\lifxlan-master\examples>python broadcast_on.py

c:\Python27\lifxlan-master\lifxlan-master\examples>python hello_world.py 2
Discovering lights...
Traceback (most recent call last):
  File "hello_world.py", line 27, in <module>
    main()
  File "hello_world.py", line 21, in main
    devices = lifx.get_lights()
  File "C:\Python27\lib\site-packages\lifxlan-0.2.3-py2.7.egg\lifxlan\lifxlan.py", line 49, in get_lights
    responses = self.broadcast_with_resp(GetService, StateService)
  File "C:\Python27\lib\site-packages\lifxlan-0.2.3-py2.7.egg\lifxlan\lifxlan.py", line 203, in broadcast_with_resp
    raise WorkflowException("Did not receive {} in response to {}".format(str(response_type), str(msg_type)))
lifxlan.device.WorkflowException: Did not receive <class 'lifxlan.msgtypes.StateService'> in response to <class 'lifxlan.msgtypes.GetService'>

```

**Comment by mclarkk** [comment]
Hey there! I was able to run lifxlan scripts on a Windows 7 machine with no problem a couple days ago.

Do you have administrative privileges on the account that you're running the scripts from? I ran the program from an admin account, and there was still an additional pop-up that I had to click to allow. My guess is that for both this issue and [issue #4] there is some kind of permissions/network settings configuration on your two computers that is preventing the script from running correctly.

**Comment by frakman1** [comment]
Yes, I have administrative priviledges on my computer. In fact, the window top bar title reads: "Administrator: Command Prompt". 
I don't get any pop-ups when running the script. I have all that sorted.
Can you please print out the results of "route print" from your Windows7 machine that works? Please indicate which network the LIFX bulbs are on if possible. I am interested in the entry for 255.255.255.255 Network Destination.
Thanks

**Comment by frakman1** [comment]
Good news.! I was able to fiddle with the routing table and ge this  (broadcast_xx.py commands) to work. Specifically, I added these lines:

```
route delete 255.255.255.255
route add 255.255.255.255 192.168.16.255
(where 192.168.16.x is the network my bulbs are on)
```

The hello_world script got further and returned some bulb data but crashed at the end  due to some print keying error. I'll update the other open issue with those details.

**Comment by mclarkk** [comment]
Interesting, I'm glad you figured that out! I hope this helps out someone else with similar issues down the line. Thanks for sticking it out.
