### ISSUE TITLE
Simple Power Toggle

### ISSUE THREAD

**Issue by eidermar** [mclarkk/lifxlan#62]
I have very limited coding knowledge and would like to write a script that does a simple power toggle - when lights are on, turn them off and vice versa - so I can control the bulbs from network events. I did investigate all the provided example files and tried to adapt them for my needs with no success. I'm sure this is very simple but still couldn't figure it out. any help is appreciated!

thank you for your help!

**Comment by plakna** [comment]
If you know the mac and ip address you could do something like this:
```python
from lifxlan import Light

light = Light('xx:xx:xx:xx:xx:xx', '10.0.0.100')
light.set_power(not light.get_power())
```

You could also search the bulb by name (but this is quite slow):
```python
from lifxlan import LifxLAN
from lifxlan import Light

lan = LifxLAN() 
light = lan.get_device_by_name('Kitchen')
light.set_power(not light.get_power())
```

I hope this helps :)

**Comment by eidermar** [comment]
Fantastic, works like a charm!
Just out of curiosity, Is there a way of doing this for ALL bulbs on the network without defining specific ones by IP, MAC or Name?

thank you very much!!!

**Comment by alex-p30** [comment]
Yes, set the destination address to be xxx.xxx.xxx.255. This will broadcast
the command to all bulbs on the subnet.

**Comment by eidermar** [comment]
Thanks guys. That helped a lot. I ended up doing it like this:

`from lifxlan import Light, LifxLAN

lifx = LifxLAN(6)

light1 = Light('xx:xx:xx:xx:xx:xx', 'xxx.xxx.xxx.xxx')
lifx.set_power_all_lights(not light1.get_power())`

Which not only toggles the bulbs but also syncs the power state to a specific master bulb. Happy camper!

**Comment by korruptcow** [comment]
I might piggy back on this one. I finally got lights working via IP. I wasn't aware you needed to import Light in the lifxlan section. Maybe that can be put in the light IP section of the description. 

My thing i want to do is a SLOW fade on and off. What's the best way to do this?

**Comment by NobleBrutus** [comment]
That should be as simple as slowly iterating the brightness (the B in HSBK) up or down with a suitable delay of your choosing between each iteration?

**Comment by korruptcow** [comment]
Hi there. I got it using the duration setting in set_power. Works fine and it was fairly easy to integrate into KODI! I had to rewrite the whole lot but it works now (only on my single bulb) but it's pretty much cool.

**Comment by hendryman** [comment]
how to i do this on a lifx light strip? the script fails with this message:

```
Traceback (most recent call last):
  File "lampe_strip_toggle.py", line 10, in <module>
    lampe.set_power(not lampe.get_power(), rapid=True)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/light.py", line 41, in get_power
    response = self.req_with_resp(LightGetPower, LightStatePower)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/device.py", line 516, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.LightStatePower'>] from d0:73:d5:26:ab:52 (Name: None) in response to <class 'lifxlan.msgtypes.LightGetPower'>

```

**Comment by mclarkk** [comment]
The code works for me, so that's good! The LIFX Z firmware tends to need a restart (power cycle) occasionally, which clears up these problems...see issue #63. Let me know if restarting the light helps!
