### ISSUE TITLE
GetVersion error [LIFX Z Firmware issue]

### ISSUE THREAD

**Issue by NaffanDroo** [mclarkk/lifxlan#63]
Hi,

I'm trying to get the code working for the first time, I've tried both pip versions and a checkout locally today.

Using the following code:
```python
from lifxlan import LifxLAN
from lifxlan import MultiZoneLight
num_lights = 2
print("Starting up lights...")
lifx = LifxLAN(num_lights, False)
multizone_lights = lifx.get_multizone_lights()
```

I get:

> Traceback (most recent call last):
>   File "party_mode.py", line 9, in <module>
>     multizone_lights = lifx.get_multizone_lights()
>   File "/srv/hass/lib/python3.4/site-packages/lifxlan/lifxlan.py", line 74, in get_multizone_lights
>     if l.supports_multizone():
>   File "/srv/hass/lib/python3.4/site-packages/lifxlan/device.py", line 369, in supports_multizone
>     self.product_features = self.get_product_features()
>   File "/srv/hass/lib/python3.4/site-packages/lifxlan/device.py", line 277, in get_product_features
>     self.vendor, self.product, self.version = self.get_version_tuple()
>   File "/srv/hass/lib/python3.4/site-packages/lifxlan/device.py", line 258, in get_version_tuple
>     response = self.req_with_resp(GetVersion, StateVersion)
>   File "/srv/hass/lib/python3.4/site-packages/lifxlan/device.py", line 508, in req_with_resp
>     raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
> lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.StateVersion'>] from MYMACADDRESS (Name: None) in response to <class 'lifxlan.msgtypes.GetVersion'>

(MAC Address is masked)

I have two LIFX Z strips on my network, I also tried using MultiZoneLight(...,...) but get the same error.

Any ideas what the problem is?

Cheers
Nathan

**Comment by ceboxsell** [comment]
Hi Nathan,
I tested on my single Z using 1.22 firmware ( make sure you have updated to that) and I had no problem. You don't need to import MultiZoneLight however.
I used -
`from lifxlan import LifxLAN
from time import sleep
num_lights = 2
print("Starting up lights...")
lifx = LifxLAN(num_lights)
bulbs = lifx.get_multizone_lights()
print(str( bulbs))
bulb = bulbs[0]
bulb.set_power("on", rapid=True)
sleep(10)
bulb.set_power("off",duration=20000)`

**Comment by ceboxsell** [comment]
Nathan I have now seen the same issue. The network side of the Z strips isn't good, they drop off the LAN often and don't return packets correctly, 1.22 makes this a lot better but I am testing on a Z that had problems and a new one was sent by LIFX, my Z which I still have is useless because after 20 mins or so it drops off the network but if I power off and on it is ok for testing for a short while.

Restart your Z units and try again once they connect. It will prob work then. If you have not updated as I said make sure you are on 1.22 (the hello_world example will show you the firmware revision)

**Comment by NaffanDroo** [comment]
Hi Chris,

Thanks for checking it out, glad it's not just me! I tried the Hello World example - it wouldnt work until I restarted them, then I managed to pull back the firmware version, both my lights are at:
```
  Host Firmware Build Timestamp: 1502237570000000000 (2017-08-09 00:12:50 UTC)
  Host Firmware Build Version: 1.22
  Wifi Firmware Build Timestamp: 1456093684000000000 (2016-02-21 22:28:04 UTC)
  Wifi Firmware Build Version: 101.62
```
I also tried your code above rather than my own and got a response out of the light:
`
Starting up lights...
[<lifxlan.multizonelight.MultiZoneLight object at 0x10fe29ad0>, <lifxlan.multizonelight.MultiZoneLight object at 0x10fe29b10>]
`
(It did perform the actions in the script).

I had imported MultiZoneLight as I was trying to directly connect to them with a hard coded connection - I was trying quite a few things before I raised the issue 😄 

Seems the restart helped - as now I've got it returning the colours with get_color_zones():
`
[(0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003), (0, 0, 18761, 3003)]
`
Do you think that the firmware still has an issue at 1.22? I guess I will just have to monitor it and raise a ticket with LIFX if it goes wrong again.

Cheers
Nathan

**Comment by natn** [comment]
Reporting the same issue and similar exception. Rebooted the LifxZ and can now enumerate it correctly with the hello world code.  

Same firmware versions as previously reported:

Host Firmware Build Timestamp: 1502237570000000000 (2017-08-09 00:12:50 UTC)
Host Firmware Build Version: 1.22
Wifi Firmware Build Timestamp: 1456093684000000000 (2016-02-21 22:28:04 UTC)
Wifi Firmware Build Version: 101.62

**Comment by mclarkk** [comment]
I also have the same chronic problem with my LIFX Z, which is on 1.22. A reboot always fixes it, but that's not a great long-term solution. They look so cool though, worth it :p

**Comment by mclarkk** [comment]
Closing this since LIFX Z firmware is now at version 2.74. I can reopen it if people still see a problem after upgrading.

**Comment by ceboxsell** [comment]
I had issues with their beta app on android not able to control the light as well as the windows app not being able to control it.
There are 2 versions of the Z controller, the original at 1.22 firmware and the newer with Crapple homekit support that is much more reliable.
You could contact their support people and tell them you are having problems controlling the light and see if they will replace your controller as they did mine recently.
