### ISSUE TITLE
UDP_BROADCAST_IP_ADDRS incorrect

### ISSUE THREAD

**Issue by jimmydevine** [mclarkk/lifxlan#73]
get_broadcast_addrs in device.py looks like it assumes the network is a /24 by replacing the last octet with 255 to create broadcast addresses.  My network is a /16 and thus recent versions of this code fail to find any of my devices which are on a different segment.

It looks like you're using netifaces to retrieve IP information and it looks like the ni.ifaddresses(iface)[ni.AF_INET][0] contains the broadcast address.

{'peer': u'127.0.0.1', 'netmask': u'255.0.0.0', 'addr': u'127.0.0.1'}
{'broadcast': u'10.10.255.255', 'netmask': u'255.255.0.0', 'addr': u'10.10.3.30'}

Any reason not to use that?

**Comment by mclarkk** [comment]
Fixed with #82! Thanks @exking!
