### ISSUE TITLE
Unable to run scripts in Python 3 IDLE - Import error

### ISSUE THREAD

**Issue by rjmason13** [mclarkk/lifxlan#75]
I've been able to launch the modules with no problem when using Python 2 IDLE, but on Python 3 i get an error anytime i try to import from lifxlan. Even the given examples give errors. They work fine with called from terminal though. Forgive me if i'm missing something simple. I ask because i want to use code with Python 3 web framework and want to make sure i wont have issues with Python 3.

**Comment by rjmason13** [comment]
Silly me. the instructions did not specify i needed to install lifxlan using pip3 to work in Python 3. Also needed to install netifaces and bitstring

**Comment by mclarkk** [comment]
Glad you figured it out! Enjoy :)
