### ISSUE TITLE
LifxLAN(num_lights)

### ISSUE THREAD

**Issue by spacelama** [mclarkk/lifxlan#76]
When doing initial discover, we supply the known num_lights to speed up discovery, but sometimes a light isn't present because it's off/packet loss, etc.  I don't want discovery to fail outright, because in all likelihood, the light I want to operate on is still working.

I've achieved this by commenting out these lines in broadcast_with_resp:
    #        if success == False:
    #            self.close_socket()
    #            raise WorkflowException("Did not receive {} in response to {}".format(str(response_type), str(msg_type)))
    #        else:

but I suspect the correct fix would be only to not raise that exception only in the discovery call, not for subsequent calls.

**Comment by mclarkk** [comment]
Assuming I understood the description correctly, the library's behavior is desireable -- I think that if discovery is told to search for a specific number of bulbs, it should throw an error if it doesn't find them all. The pattern I would suggest is to handle the error and re-run discovery until discovery finds everything. After all, even if a bulb is still working, if the program hasn't found it through discovery (and assuming you don't have the IP and MAC address) the program won't be able to operate on it anyway. Does that make sense, or did I misunderstand the problem?

**Comment by spacelama** [comment]
It's more for when you have a bunch of bulbs, some of them unreliable (or turned off manually), but you still want to be able to reliably discover the one you want to operate on, regardless of how many bulbs are physically powered on and responding.  But you don't want to incur the penalty of waiting for a long timeout when the bulb you're acting on responded with its UDP packet in the usual 30ms.  If you supply a smaller number, then you're bulb might not be the one returned.

What I ended up using was:
```
    # get devices
    print("Discovering lights...")
    try:
        devices = lifx.get_lights()
    except:
        print "Some lights are off - falling back to slow discovery"
        lifx = LifxLAN(None)
        devices = lifx.get_lights()
```

I just wish that was the default behaviour.  Clearly, if the bulb you're wanting to act on is not available, then the next call to devices[...].get_power() is going to fail, and that's fine.

**Comment by mclarkk** [comment]
All great points! I'll take a look at how discovery works shortly, and I'll post an update here when I've made changes to the library.

**Comment by mclarkk** [comment]
I made changes to how discovery works! The semantics should work the way you'd like now. If the discovery hears back from all the lights it will move on quickly, but if it doesn't hear back from that many lights before the timeout, no problem, discovery will just give you what it found. The updates are available via pip and git. Let me know what you think!

**Comment by spacelama** [comment]
Excellent - seems to work well.
