### ISSUE TITLE
utils function RGBtoHSBK needs floats during calculations or answer is incorrect.

### ISSUE THREAD

**Issue by CAReeser** [mclarkk/lifxlan#78]
[utils.txt](https://github.com/mclarkk/lifxlan/files/1729142/utils.txt)

**Comment by mclarkk** [comment]
Ah, I'm guessing utils.py was tested only with Python 3, which doesn't require the float conversions. Did you want to submit a pull request and get credit for contributing?

**Comment by CAReeser** [comment]
Will do.


Cliff

**Comment by CAReeser** [comment]
If you will review my changes, I'll let you sponsor the pull request. I'm not a professional.
Cliff
