### ISSUE TITLE
Not working under FreeBSD 11.1

### ISSUE THREAD

**Issue by Dismounted** [mclarkk/lifxlan#79]
A bit of a weird issue... I'm running the `hello_world.py` script under FreeBSD 11.1 and Ubuntu 16.04 - works fine in Ubuntu but fails to discover any devices in FreeBSD.

Tried both Python 2.7 and 3.6 in FreeBSD, works on neither. I'm thinking it is a peculiarity with network access under FreeBSD but I don't receive any error messages.

I don't have enough understanding of how it's all put together to do further debugging by myself, but can assist if someone can point me in the right direction.

**Comment by exking** [comment]
just tried on FreeBSD, works fine... what you seeing?

**Comment by Dismounted** [comment]
Weird then... running `hello_world.py` under my install gives this:
```
$ python3 hello_world.py

Discovery will go much faster if you provide the number of lights on your LAN:
  python hello_world.py <number of lights on LAN>

Discovering lights...

Found 0 light(s):

```
No error messages seen in the output. Correctly detects 1 light under Ubuntu.

**Comment by Dismounted** [comment]
Some interesting findings: looks like my installation has an issue with receiving responses from the light. Targeting a light directly and setting its power with `rapid=True` works fine, but does not work with `rapid=False`. Both versions work correctly under Ubuntu.

_As per `light.py`, if `rapid=True` then the action is `fire_and_forget`, and if `rapid=False` then the action is `req_with_ack`._

Here's my test script:
```python
import lifxlan

mylight = lifxlan.Light("d0:73:d5:XX:XX:XX", "10.0.XXX.XXX")
mylight.set_power("on", rapid=False)
```

I also now see two different types of errors when `rapid=False` (only one appears each time when executing the script, I never see both appear):
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    mylight.set_power("on", rapid=False)
  File "/usr/local/lib/python3.6/site-packages/lifxlan/light.py", line 52, in set_power
    self.req_with_ack(LightSetPower, {"power_level": 65535, "duration": duration})
  File "/usr/local/lib/python3.6/site-packages/lifxlan/device.py", line 471, in req_with_ack
    self.req_with_resp(msg_type, Acknowledgement, payload, timeout_secs, max_attempts)
  File "/usr/local/lib/python3.6/site-packages/lifxlan/device.py", line 494, in req_with_resp
    self.sock.sendto(msg.packed_message, (ip_addr, self.port))
OSError: [Errno 64] Host is down
```
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    mylight.set_power("on", rapid=False)
  File "/usr/local/lib/python3.6/site-packages/lifxlan/light.py", line 52, in set_power
    self.req_with_ack(LightSetPower, {"power_level": 65535, "duration": duration})
  File "/usr/local/lib/python3.6/site-packages/lifxlan/device.py", line 471, in req_with_ack
    self.req_with_resp(msg_type, Acknowledgement, payload, timeout_secs, max_attempts)
  File "/usr/local/lib/python3.6/site-packages/lifxlan/device.py", line 516, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.Acknowledgement'>] from d0:73:d5:XX:XX:XX (Name: None) in response to <class 'lifxlan.msgtypes.LightSetPower'>
```

**Comment by Dismounted** [comment]
Okay, worked it out - traced it back to an issue with `get_broadcast_addrs()`. The function currently assumes /24, and so no broadcasts work when your network is not /24. (My LAN is /16, and everything magically worked because my Ubuntu installation is a VM with a NATed network connection, hence the broadcasts were correctly re-translated by the VM software.)

A secondary issue involving `device.py` always sending broadcasts for requests that require a response stopped the test script above from working correctly, even though an IP for the light was specified. This did not affect "fire and forget" sends, which do not send broadcasts in this context (hence `rapid=True` worked).

I will patch and submit a PR shortly! 🙂
