### ISSUE TITLE
Set hue/sat/brightness/kelvin individually

### ISSUE THREAD

**Issue by mclarkk** [mclarkk/lifxlan#8]
This is unfortunately not supported at all by the low-level LAN protocol that the LIFX bulbs use. The bulbs require that all four values be present in a SetColor message. However, I could fake the ability to set hue/saturation/brightness/kelvin by getting the current state of the bulbs first and then supplying the other values based on what the bulb said, but it would add some latency. I'm not sure how much -- I might be able to do it quickly enough. It's worth investigating.

**Comment by EJH2** [comment]
yes, i would specifically like you to add a light.set_brightness() function in the future. would make future codes all the better
