### ISSUE TITLE
[Request] Increase default timeout.

### ISSUE THREAD

**Issue by frakman1** [mclarkk/lifxlan#81]
In a crowded WiFi spectrum, the finder times out without finding any of my bulbs. I have had to increase the default timeout [here](https://github.com/mclarkk/lifxlan/blob/master/lifxlan/device.py#L34) before it would find my bulbs.

Any chance you could increase it in your next release?

**Comment by bsileo** [comment]
I may be seeing this same problem - I am getting very inconsistent discovery of bulbs. I have 22 on my network along with quite a few other devices. LIFX app sees all 22 but not lifxlan.

**Comment by mclarkk** [comment]
Done! The default timeout for `discover()` is now the global `DEFAULT_TIMEOUT` in `device.py` (not sure how that 0.3 default value snuck by), and `DEFAULT_TIMEOUT` has been set to 1 second. I hope that works better!
