### ISSUE TITLE
Lifx Tile Support

### ISSUE THREAD

**Issue by natn** [mclarkk/lifxlan#84]
The current version does not support Lifx Tile.

Is anyone working on this (Product ID 55)?  It appears to require a new message type and has a new "chain" product attribute.

https://github.com/LIFX/products/blob/master/products.json
https://lan.developer.lifx.com/docs/tile-control
https://lan.developer.lifx.com/docs/tile-messages

**Comment by mclarkk** [comment]
I'd be happy to add tile support, especially since it will take a substantial amount of effort that requires a fairly intimate understanding of the library. The main issue is obtaining some tiles to test on. A friend of mine just set some up in their apartment and I've schedule hacking time this Sunday, so hopefully you will see this soon!

**Comment by natn** [comment]
That would be great!  If there is anything I can do to help let me know, I
have a functional tile setup as well, so if you have test cases you would
like me to run I would be glad to.

**Comment by mclarkk** [comment]
All right! There is now a rough but complete pass at tile support in the branch `tiles`. I encourage you to check out that branch and play around with it. The useful functions are in `lifxlan/tilechain.py` and There is an example program called `examples/tilechain_falling_rainbow.py` that looks prettyyyy cool. The most useful functions to start with:

```
get_tile_colors(start_index, [someoptionalstuff])
set_tile_colors(start_index, colors, [someoptionalstuff])
get_canvas_dimensions(num_tiles_in_light)
project_matrix(hsvk_matrix, num_tiles_in_light, [someoptionalstuff]

```

The `project_matrix` function takes in a 2D matrix of canvas_dimensions size with HSVK color tuples as the elements, and projects each colors onto the corresponding light pixel. See the falling rainbow program for an example.

Tragically, the lower-level messages don't seem to be returning the total number of lights correctly, so for now some higher-level functions require that you explicitly provide the number of tiles in the light. Once I can iron out that weird protocol issue and add some input validation, the new features might be ready for primetime.

**Comment by natn** [comment]
Its working pretty well, but `project_matrix `and `set_tile_colors` were too slow for my liking so I did the following:

- moved the `req_with_resp(GetDeviceChain, StateDeviceChain)` calls out of `get_tile_info` and `get_tile_count` (whenever that works :-) ),  put them in the `TileChain  __init__ ` method and assigned the response to an instance attribute.    Then methods can access the response attribute instead of reaching out to the device over and over, as I don't think the device chain will change dynamically very often.  Maybe `set_tile_coordinates` should refresh the `GetDeviceChain_response` attribute though. (although I'm not sure why I would use that method yet)

```
class TileChain(Light):
    def __init__(self, mac_addr, ip_addr, service=1, port=56700, source_id=os.getpid(), verbose=False):
        super(TileChain, self).__init__(mac_addr, ip_addr, service, port, source_id, verbose)
        self.GetDeviceChain_response = self.req_with_resp(GetDeviceChain, StateDeviceChain)

    # returns information about all tiles
    def get_tile_info(self):
        tiles = []
        for tile in self.GetDeviceChain_response.tile_devices:
            t = Tile(tile["user_x"], tile["user_y"], tile["width"], tile["height"], tile["device_version_vendor"], tile["device_version_product"], tile["device_version_version"], tile["firmware_build"], tile["firmware_version"])
            tiles.append(t)
        return tiles[:self.GetDeviceChain_response.total_count]

    # should return the number of tiles in the chain...right?
    def get_tile_count(self):
        self.total_count = self.GetDeviceChain_response.total_count
        return self.total_count

```
- Added the rapid parameter and associated logic to set_tile_colors and project_matrix

That seems to speed up things quite a bit.

Thanks for doing this! I am having a bunch of fun...

**Comment by mclarkk** [comment]
Excellent! I thought about caching a bunch of the results, particularly the tile map, but by then it was already about 2 or 3am :) Glad to know there are speedup gains to be made!

There is at least one legitimate use for the `set_tile_coordinates` function -- there is another function in there called `recenter_coordinates`, which goes through the tiles and makes sure that one of them is at 0, 0. One of my friend's lights had coordinates where all of the y coordinates were shifted by -0.5 (the central tile was at 0, -0.5), so that let me recenter everything around 0, 0. It wasn't necessary, but it made it easier to read the tile info.

**Comment by mclarkk** [comment]
I fixed the `num_tiles` thing -- turns out the official docs had a couple fields in the wrong order. I pushed another update (without testing!! 😱) so all those functions that originally required `num_tiles` as an argument should be able to get it automatically now. All of the important changes are in `msgtypes.py` and `unpack.py`. If you could test the `get_tile_count()` function in `tilechain.py` and let me know whether or not it returns a sensible number for your lights, that would be great. You should be able to use either the most recently pushed version of `tilechain.py` or your local copy with the caching behavior, so long as `msgtypes.py` and `unpack.py` are updated.

**Comment by natn** [comment]
Awesome! I will merge the updated code tonight and give it a whirl and let
you know.

**Comment by natn** [comment]
Ok, so I merged the changes but did not run as is.  Here is what I get:

```
Traceback (most recent call last):
  File "C:/Users/natn/PycharmProjects/lifxlan/examples/tile_dots.py", line 54, in <module>
    main()
  File "C:/Users/natn/PycharmProjects/lifxlan/examples/tile_dots.py", line 10, in main
    t = TileChain("d0:73:d5:33:14:21", "192.168.1.143")
  File "C:\Users\natn\PycharmProjects\lifxlan\lifxlan\tilechain.py", line 10, in __init__
    self.GetDeviceChain_response = self.req_with_resp(GetDeviceChain, StateDeviceChain)
  File "C:\Users\natn\PycharmProjects\lifxlan\lifxlan\device.py", line 508, in req_with_resp
    response = unpack_lifx_message(data)
  File "C:\Users\natn\PycharmProjects\lifxlan\lifxlan\unpack.py", line 283, in unpack_lifx_message
    total_count = struct.unpack("B", [payload_str[-1]])[0]
TypeError: a bytes-like object is required, not 'list'
```


The contents of `payload_str` is at that point:
```
b'\x00\xb3\x0f)\x01L\x00\x00\x00\x00\x00\x98@\x00\x00\x10\xc0\x08\x082\x01\x00\x00\x007\x00\x00\x00\n\x00\x00\x00\x00\x04\x8bz\x15\x89\x06\x15\x00\x04\x8bz\x15\x89\x06\x15,\x00\x03\x00\x01\x00\x00\x00\xd2\x0f\xc2\x01\x00\xff\x00\x00\x00\x00p@\x00\x00\xa0\xbf\x08\x082\x01\x00\x00\x007\x00\x00\x00\n\x00\x00\x00\x00\x04\x8bz\x15\x89\x06\x15\x00\x04\x8bz\x15\x89\x06\x15,\x00\x03\x00\x01\x00\x00\x00^\x0f\xcc\x00\xb2\xff\x00\x00\x00\x000@\x00\x00\x80\xbe\x08\x082\x01\x00\x00\x007\x00\x00\x00\n\x00\x00\x00\x00\x04\x8bz\x15\x89\x06\x15\x00\x04\x8bz\x15\x89\x06\x15,\x00\x03\x00\x01\x00\x00\x00\xc6\x0f\xf6\xff\xbb\xff\x00\x00\x00\x00\xe0?\x00\x00@?\x08\x082\x01\x00\x00\x007\x00\x00\x00\n\x00\x00\x00\x00\x04\x8bz\x15\x89\x06\x15\x00\x04\x8bz\x15\x89\x06\x15,\x00\x03\x00\x01\x00\x00\x00y\x0f|\x00\x06\xff\x00\x00\x00\x00@?\x00\x00\x80\xbe\x08\x082\x01\x00\x00\x007\x00\x00\x00\n\x00\x00\x00\x00\x04\x8bz\x15\x89\x06\x15\x00\x04\x8bz\x15\x89\x06\x15,\x00\x03\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05

```

If I change `total_count = struct.unpack("B", [payload_str[-1]])[0]` to `total_count = payload_str[-1]` that sets `total_count` to 5 as expected.  I cleaned up a couple of stray `num_tiles` params in a few calls in `tilechain.py` and things are working.

**Comment by natn** [comment]
I'm pretty sure `payload_str[-1]` alone isn't just grabbing the last byte, so its working, but probably not safe when that 16th tile is connected.  

After messing around a bit I came up with this `total_count = struct.unpack("B", payload_str[len(payload_str) - 1:len(payload_str)])[0]`  which returns just the last byte and should be safe.  

I wonder if there is a cleaner way to get that last byte, since `list[-1]` doesn't just return the last byte, at least in Python 3.6.4

**Comment by mclarkk** [comment]
Sure! The cleaner way would be to just give it the indices. The proper indices can be calculated using using `tilesize_bytes` from earlier. There might be an off-by-one error, but the start index should always be 1 + 16*55:

```
total_count = struct.unpack("B", payload_str[881, 882])[0] 
```
Does that work?

**Comment by natn** [comment]
I thought there maybe was a need to index the end of the string, rather than from the start, but that works fine!

**Comment by mclarkk** [comment]
Got to play with the Tiles again for a little bit. Today's efforts were mostly to catch the branch up with your suggestions:

- Fixed `unpack.py` to get `total_count` and cleaned up the `num_tiles` references.
- Added caching for `get_tile_info()`, `get_tile_count()`, `get_tile_map()`, and `get_canvas_dimensions()` calls.
- Made it so `set_tile_coordinates()` updates cached information about the tiles.
- Added multi-threading for methods that update the whole tilechain light at once so each tile changes more or less at the same time (applies to `project_matrix()` and `set_tilechain_colors()`).
- Added `rapid` flag and associated logic.
- Added some input validation.
- Added methods for getting and setting the colors for the entire TileChain that are meant to be used for saving and restoring the original colors before and after a light show.

The falling rainbow example is WAY faster now!

**Comment by mclarkk** [comment]
All right, I added documentation and merged into master, so I'm declaring Tiles supported and I'm closing this issue. For additional feature requests or bugs related to the Tiles, let's open up new issues. Thanks so much for your help!!
