### ISSUE TITLE
get_lights() Aborts With Exception

### ISSUE THREAD

**Issue by natn** [mclarkk/lifxlan#85]
Several of my white Lifx Bulbs, mostly White 800(LV) and one White 900(BR30) type bulb caused the following exception when get_lights() was called.  The exception prevented any additional lights from being discovered, unless get_lights() was called again, then only a subset of working lights were discovered.  It would be useful, to have the discovery continue on to the rest of the lights on an error and report the MAC addresses and any other info that might have been received from lights that did not respond properly rather than raising an exception and aborting the discovery.  

To test this concept I disabled some of the error handling in the devices.py code and inserted default values for version, product and vendor if the attributes were not received from the GetVersion call.  This allowed the rest of the working lights to be discovered.

Interestingly all of the lights were responding properly to commands from the android app and received cloud commands from Alexa and Smartthings without issues, so this is could be a discovery only issue.

Once the problem lights were mains power cycled they then responded normally to the get_lights() discovery and all lights were reported in the unmodified code.

Bulbs affected are running firmware v1.22

Example exception stack trace:

>>> lifx = LifxLAN()
>>> devices = lifx.get_lights()
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    devices = lifx.get_lights()
  File "C:\Users\natn\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lifxlan\lifxlan.py", line 43, in get_lights
    self.discover_devices()
  File "C:\Users\natn\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lifxlan\lifxlan.py", line 61, in discover_devices
    if device.is_light():
  File "C:\Users\natn\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lifxlan\device.py", line 359, in is_light
    self.vendor, self.product, self.version = self.get_version_tuple()
  File "C:\Users\natn\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lifxlan\device.py", line 258, in get_version_tuple
    response = self.req_with_resp(GetVersion, StateVersion)
  File "C:\Users\natn\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lifxlan\device.py", line 518, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.StateVersion'>] from d0:73:d5:11:4b:03 (Name: None) in response to <class 'lifxlan.msgtypes.GetVersion'>

**Comment by natn** [comment]
I added a try:except:pass block around the is_light() call in lifxlan that fails if a device does not respond during discovery.  This allows the discovery to complete; devices that fail to respond are still registered as devices, while all the lights that can be discovered, are.

Still not sure why a few of my lights are doing this.  Its the same few lights every time, while the rest seem to have no issues.  Same firmware, good wifi signal.  Power cycling the light fixes it every time.

            **try:**
                if device.is_light():
                    if device.supports_multizone():
                        device = MultiZoneLight(r.target_addr, r.ip_addr, r.service, r.port, self.source_id, self.verbose)
                    else:
                        device = Light(r.target_addr, r.ip_addr, r.service, r.port, self.source_id, self.verbose)
                    self.lights.append(device)
            **except:
                pass**

**Comment by mclarkk** [comment]
The LIFX Z firmware does the same thing (see #63). The LIFX Z lights tend to get into a state where it raises GetVersion errors, which is fixed upon power cycling the light. I'm not sure if the problem is on the library side, the firmware side, or some weird interaction between them. The try/except block is a good patch to keep discovery working, but there is something deeper to probe here.

**Comment by mclarkk** [comment]
@gazhay `lifxlan` is finding the lights too. The problem is that the lights aren't responding to a GetVersion message after being found, so `lifxlan` can't figure out their capabilities and decide whether they should be constructed as Light, MultiZoneLight, or TileChain objects.

**Comment by mclarkk** [comment]
I made some changes to how discovery works. If you could all update your `lifxlan` libraries (either through pip or with a git pull and reinstall) and let me know if you're still experiencing the same problems, that would be great!!

**Comment by natn** [comment]
So far no discovery issues.  Thanks!
