### ISSUE TITLE
Example code (rainbow_all.py) error

### ISSUE THREAD

**Issue by frakman1** [mclarkk/lifxlan#98]
I get this error when running the rainbow_all.py example on my Mac:

```bash
(virtualenv)[~/git/myAppJar/virtualenv/lifx-lan-gui/lifxlan/examples] branch:(master*)
$python3 rainbow_all.py

Discovery will go much faster if you provide the number of lights on your LAN:
  python rainbow_all.py <number of lights on LAN>

Discovering lights...
Traceback (most recent call last):
  File "rainbow_all.py", line 56, in <module>
    main()
  File "rainbow_all.py", line 24, in main
    original_colors = lifx.get_color_all_lights()
  File "/Users/frak/git/myAppJar/virtualenv/lib/python3.6/site-packages/lifxlan/lifxlan.py", line 175, in get_color_all_lights
    for light in self.lights:
TypeError: 'NoneType' object is not iterable
```

**Comment by frakman1** [comment]
This appears to work on Windows but fails on my Mac. Another user has reported the same issue on his Mac. Originally found in the lifx-lan-gui project that uses this code in the "All Rainbow" Button functionality.

**Comment by mclarkk** [comment]
Looks like it didn't find any lights! Does that happen every time you try to run the script?

**Comment by frakman1** [comment]
Hmm. I am getting inconsistent results on the same Mac and same network. It seems to have worked once I pulled the latest and re-installed via `python setup.py install`
