### ISSUE TITLE
Emoji in device Label causes Exception

### ISSUE THREAD

**Issue by grepmyps** [mclarkk/lifxlan#99]
Howdy,

Found an issue where when a light has a label that has an emoji character, for example, 🍆, LightState.get_payload() sends invalid data to bitstring, which throws an exception.

This appears to be due to utilizing ord() to convert a string to bytes when the string contains unicode characters.

In msgtypes.py:395, I changed this:

   label = b"".join(little_endian(bitstring.pack("8", ord(c))) for c in self.label)

to this:

   label = b"".join(little_endian(bitstring.pack("8", c)) for c in self.label.encode())

which fixed the issue.  Not sure where else this may crop up, however.

**Comment by mclarkk** [comment]
Excellent! It crops up in a lot of places, but will be well worth the change to support unicode. Thanks for the fix, will roll it into the library shortly.

**Comment by mclarkk** [comment]
Added in the fix everywhere! New version of the library with unicode support was pushed to pip. Let me know if I missed anything!
